--- #YAML:1.0
name:               Data-TreeDumper
version:            0.38
abstract:           Improved replacement for Data::Dumper. Powerful filtering capability.
author:
    - Khemir Nadim ibn Hamouda. <nadim@khemir.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Check::ISA:       0
    Class::ISA:       0
    Devel::Size:      0.58
    Sort::Naturally:  0
    Term::Size:       0.2
    Text::Wrap:       2001.0929
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
